using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace EverendForge.Unity.Editor
{
    public sealed class EverendSinpoInkGenerator
    {
        private readonly EverendNarrativeCatalog catalog;
        private readonly Func<string, string> nativeEventId;
        private readonly List<string> errors = new List<string>();

        public EverendSinpoInkGenerator(EverendNarrativeCatalog source, Func<string, string> eventIdResolver)
        {
            catalog = source; nativeEventId = eventIdResolver;
        }

        public IReadOnlyList<string> Errors => errors;

        public string GenerateGlobals(string includePath)
        {
            var output = new StringBuilder();
            output.AppendLine("// GENERATED BY Everend Forge. Do not edit.");
            if (!string.IsNullOrWhiteSpace(includePath)) output.AppendLine("INCLUDE " + includePath);
            foreach (var variable in catalog.Package.Variables.OrderBy(x => x.Key, StringComparer.Ordinal))
            {
                if (!(variable.Value is bool) && !(variable.Value is long) && !(variable.Value is double) && !(variable.Value is string))
                {
                    errors.Add("Variable '" + variable.Key + "' has an unsupported default value for Ink."); continue;
                }
                output.Append("VAR ").Append(InkIdentifier(variable.Key)).Append(" = ").Append(InkLiteral(variable.Value)).AppendLine();
            }
            return output.ToString();
        }

        public string GenerateEvent(EverendEvent narrativeEvent)
        {
            var output = new StringBuilder();
            output.AppendLine("// GENERATED BY Everend Forge. Source event: " + narrativeEvent.Id);
            output.AppendLine("INCLUDE EverendGlobals.ink");
            var knot = Knot(narrativeEvent.Id);
            output.AppendLine("-> " + knot).AppendLine().Append("=== ").Append(knot).AppendLine(" ===");

            if (!string.IsNullOrWhiteSpace(narrativeEvent.Text?.Content)) EmitLine(output, narrativeEvent.Text.Content, null);
            foreach (var beat in narrativeEvent.DialogueBeats)
            {
                EverendScriptBlock block;
                if (!catalog.TryGetBlock(beat.ScriptId, beat.BlockId, out block)) { errors.Add("Event '" + narrativeEvent.Id + "' references missing script block '" + beat.ScriptId + "/" + beat.BlockId + "'."); continue; }
                EmitConditionalLine(output, beat.DisplayCondition, block.Content, block.SpeakerRef);
            }

            if (narrativeEvent.Decisions.Count > 1) errors.Add("Event '" + narrativeEvent.Id + "' has more than one decision. sinpo-v0.1 supports one decision per event.");
            if (narrativeEvent.Decisions.Count == 1) EmitDecision(output, narrativeEvent, narrativeEvent.Decisions[0]);
            else
            {
                var nodeId = narrativeEvent.Id;
                if (catalog.GetOutgoingTransitions(nodeId).Count == 0 && narrativeEvent.DialogueBeats.Count > 0) nodeId = "beat:" + narrativeEvent.Id + ":" + narrativeEvent.DialogueBeats[narrativeEvent.DialogueBeats.Count - 1].Id;
                EmitTransitions(output, narrativeEvent, null, nodeId);
            }
            return output.ToString();
        }

        private void EmitDecision(StringBuilder output, EverendEvent source, EverendDecision decision)
        {
            if (decision.Outcomes.Count == 0) { errors.Add("Decision '" + decision.Id + "' has no outcomes."); return; }
            foreach (var outcome in decision.Outcomes)
            {
                var label = string.IsNullOrWhiteSpace(outcome.VisibleText) ? outcome.Name : outcome.VisibleText;
                if (string.IsNullOrWhiteSpace(label)) { errors.Add("Outcome '" + outcome.Id + "' has no visible text."); continue; }
                var condition = Condition(outcome.Availability, "outcome '" + outcome.Id + "'");
                output.Append("* "); if (!string.IsNullOrEmpty(condition)) output.Append('{').Append(condition).Append("} ");
                output.Append('[').Append(EscapeLine(label)).AppendLine("]");
                EmitConsequences(output, outcome.Consequences, "outcome '" + outcome.Id + "'");
                EmitTransitions(output, source, outcome.TargetNodeId);
            }
        }

        private void EmitTransitions(StringBuilder output, EverendEvent source, string explicitTarget, string sourceNodeId = null)
        {
            var transitions = catalog.GetOutgoingTransitions(sourceNodeId ?? source.Id).ToList();
            if (!string.IsNullOrWhiteSpace(explicitTarget))
            {
                // PathBranching may point an outcome to the current event, then use its ordered event transitions.
                // When it points directly to an event, prefer that explicit target.
                var explicitTransitions = transitions.Where(x => x.To == explicitTarget).ToList();
                if (explicitTransitions.Count > 0) transitions = explicitTransitions;
            }
            if (transitions.Count == 0)
            {
                if (IsFinal(source)) { output.AppendLine("-> END"); return; }
                errors.Add("Event '" + source.Id + "' has no supported outgoing transition or final marker."); return;
            }

            var ordered = transitions.OrderBy(x => x.Order).ToList();
            var fallbackSeen = false;
            foreach (var transition in ordered)
            {
                var condition = Condition(transition.Conditions, "transition '" + transition.Id + "'");
                if (string.IsNullOrEmpty(condition))
                {
                    if (fallbackSeen) errors.Add("Event '" + source.Id + "' has multiple fallback transitions.");
                    fallbackSeen = true;
                }
                else if (fallbackSeen) errors.Add("Event '" + source.Id + "' has a conditional transition after its fallback.");
            }
            if (ordered.Count > 1 && !fallbackSeen) errors.Add("Event '" + source.Id + "' has conditional transitions but no fallback.");
            if (ordered.Count == 1 && string.IsNullOrEmpty(Condition(ordered[0].Conditions, "transition '" + ordered[0].Id + "'"))) { EmitTransition(output, ordered[0]); return; }

            var first = true;
            foreach (var transition in ordered)
            {
                var condition = Condition(transition.Conditions, "transition '" + transition.Id + "'");
                if (first) { output.Append("{ "); first = false; }
                else output.Append("- ");
                if (!string.IsNullOrEmpty(condition)) output.Append(condition).Append(": ");
                output.AppendLine(); EmitTransition(output, transition);
            }
            output.AppendLine("}");
        }

        private void EmitTransition(StringBuilder output, EverendTransition transition)
        {
            EmitConsequences(output, transition.Consequences, "transition '" + transition.Id + "'");
            EverendEvent destination;
            if (!catalog.TryGetEvent(transition.To, out destination)) { errors.Add("Transition '" + transition.Id + "' targets unsupported node '" + transition.To + "'. Only event-to-event transitions are supported."); return; }
            if (!string.Equals(destination.SequenceId, GetSequenceId(transition.From), StringComparison.Ordinal)) errors.Add("Transition '" + transition.Id + "' crosses sequences. sinpo-v0.1 requires a single Unity SequenceData.");
            output.Append("~ SetNextEvent(\"").Append(nativeEventId(destination.Id)).AppendLine("\")");
            output.AppendLine("-> END");
        }

        private string GetSequenceId(string nodeId)
        {
            EverendEvent owner;
            if (catalog.TryGetEvent(nodeId, out owner)) return owner.SequenceId;
            if (nodeId != null && nodeId.StartsWith("beat:", StringComparison.Ordinal))
            {
                var payload = nodeId.Substring("beat:".Length); var marker = payload.LastIndexOf(':');
                if (marker > 0 && catalog.TryGetEvent(payload.Substring(0, marker), out owner)) return owner.SequenceId;
            }
            return string.Empty;
        }
        private void EmitConditionalLine(StringBuilder output, IReadOnlyDictionary<string, object> conditionData, string content, string speaker)
        {
            var condition = Condition(conditionData, "dialogue beat");
            if (string.IsNullOrEmpty(condition)) { EmitLine(output, content, speaker); return; }
            output.Append("{ ").Append(condition).Append(": "); EmitLine(output, content, speaker); output.AppendLine(" }");
        }
        private static void EmitLine(StringBuilder output, string content, string speaker)
        {
            if (string.IsNullOrWhiteSpace(content)) return;
            foreach (var line in content.Replace("\r\n", "\n").Split('\n'))
            {
                if (string.IsNullOrWhiteSpace(line)) continue;
                output.Append(EscapeLine(line));
                if (!string.IsNullOrWhiteSpace(speaker)) output.Append(" #speaker:").Append(InkIdentifier(speaker));
                output.AppendLine();
            }
        }
        private void EmitConsequences(StringBuilder output, IReadOnlyList<IReadOnlyDictionary<string, object>> values, string context)
        {
            foreach (var value in values)
            {
                var type = Read(value, "type", "kind", "op");
                var variable = Read(value, "variable", "variableId", "key", "name");
                object assigned;
                if ((type == "setVariable" || type == "set" || type == "assign") && TryRead(value, out assigned, "value", "newValue")) output.Append("~ ").Append(InkIdentifier(variable)).Append(" = ").Append(InkLiteral(assigned)).AppendLine();
                else if ((type == "incrementVariable" || type == "increment") && TryRead(value, out assigned, "amount", "value")) output.Append("~ ").Append(InkIdentifier(variable)).Append(" += ").Append(InkLiteral(assigned)).AppendLine();
                else errors.Add("Unsupported consequence in " + context + ". Only setVariable and incrementVariable are supported.");
            }
        }
        private string Condition(IReadOnlyDictionary<string, object> value, string context)
        {
            if (value == null || value.Count == 0) return string.Empty;
            var type = Read(value, "type", "kind", "op");
            if (type == "all" || type == "and" || value.ContainsKey("all")) return JoinConditions(value, value.ContainsKey("all") ? "all" : "conditions", " && ", context);
            if (type == "any" || type == "or" || value.ContainsKey("any")) return JoinConditions(value, value.ContainsKey("any") ? "any" : "conditions", " || ", context);
            if (type == "not" || value.ContainsKey("not")) { object nested; return TryRead(value, out nested, value.ContainsKey("not") ? "not" : "condition") && nested is Dictionary<string, object> ? "!(" + Condition((Dictionary<string, object>)nested, context) + ")" : UnsupportedCondition(context); }
            var variable = Read(value, "variable", "variableId", "key", "name"); var operation = Read(value, "operator", "comparison"); object compared;
            if (string.IsNullOrWhiteSpace(variable) || !TryRead(value, out compared, "value", "expected")) return UnsupportedCondition(context);
            switch (operation) { case "==": case "=": case "equals": return InkIdentifier(variable) + " == " + InkLiteral(compared); case "!=": case "notEquals": return InkIdentifier(variable) + " != " + InkLiteral(compared); case ">": case ">=": case "<": case "<=": return InkIdentifier(variable) + " " + operation + " " + InkLiteral(compared); default: return UnsupportedCondition(context); }
        }
        private string JoinConditions(IReadOnlyDictionary<string, object> value, string field, string separator, string context)
        {
            object list; if (!TryRead(value, out list, field) || !(list is List<object>)) return UnsupportedCondition(context);
            var pieces = new List<string>(); foreach (var child in (List<object>)list) { var map = child as Dictionary<string, object>; if (map == null) return UnsupportedCondition(context); pieces.Add("(" + Condition(map, context) + ")"); }
            return pieces.Count == 0 ? UnsupportedCondition(context) : string.Join(separator, pieces);
        }
        private string UnsupportedCondition(string context) { errors.Add("Unsupported condition in " + context + "."); return "false"; }
        private static bool IsFinal(EverendEvent narrativeEvent) { return string.Equals(narrativeEvent.Type, "final", StringComparison.OrdinalIgnoreCase); }
        private static string Knot(string id) { return "PB_" + InkIdentifier(id); }
        private static string InkIdentifier(string value) { var result = new StringBuilder(); foreach (var character in value ?? string.Empty) result.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_'); return result.Length == 0 ? "unnamed" : result.ToString(); }
        private static string InkLiteral(object value) { if (value is bool) return (bool)value ? "true" : "false"; if (value is string) return "\"" + ((string)value).Replace("\\", "\\\\").Replace("\"", "\\\"") + "\""; return Convert.ToString(value, CultureInfo.InvariantCulture); }
        private static string EscapeLine(string value) { return value.Replace("\r", " ").Replace("\n", " ").Trim(); }
        private static string Read(IReadOnlyDictionary<string, object> value, params string[] keys) { object result; return TryRead(value, out result, keys) ? Convert.ToString(result, CultureInfo.InvariantCulture) : string.Empty; }
        private static bool TryRead(IReadOnlyDictionary<string, object> value, out object result, params string[] keys) { foreach (var key in keys) if (value != null && value.TryGetValue(key, out result) && result != null) return true; result = null; return false; }
    }
}
